React capstone project - Metrics webapp
JoffreyNK/phone-store pull request #2
Opened 2022-08-04 05:55 UTC by JoffreyNK

### React capstone project - Metrics webapp

- The project is a single-page application (SPA) built with React and Redux.
- The data is retrieved from the API and stored in the Redux store.
- I filter the data that I retrieve from the API using a Filter stateless component.
- Every page (the main page and the pages for each item) have a unique route within the SPA.
- The project is deployed and accessible online on netlify (the link to the online version app is in my README file).

2022-08-04 16:16 UTC, youmari requested changes
Hi @JoffreyNK , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

### Highlights
✅ PRO PR
✅ Git flow
✅ Following the design provided

## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-08-04 16:16 UTC, youmari commented on README.md
> +
- [ ] It would be better to give some credit to the owner of the design as in the requirements

2022-08-04 16:16 UTC, youmari commented on src/components/PhoneBrands.js
> +
- [ ] It would be better if you add a search bar that can filter phones by their names as in the requirements so Please I encourage you to do that

2022-08-04 16:16 UTC, youmari commented on src/components/__test__/PhoneBrands.test.js
> +  });
- [ ] you should write more tests for most components Also you should write tests for some pure functions in Redux code.

2022-08-04 23:16 UTC, Davidosky007 requested changes
Hi @JoffreyNK 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* Good commit messages 👍 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidosky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-04 23:16 UTC, Davidosky007 commented on README.md
> +This is my original work and no where else you can find it. but I have used some public materials which you can find down
* Like the previous reviewer mentioned kindly give appropriate credit to the author of the design which you have used for this project. [Refer to the project requirements here ](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=Original%20design%20idea,of%20your%20project.)

2022-08-05 05:57 UTC, muneebulrehman approved these changes
Hi @JoffreyNK , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- No linter errors
- Good follow-up with the previous reviewers.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-05 11:49 UTC, merged